# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kartik Asooja
brief-intro:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kasooja.github.io" # the base hostname & protocol for your site
encoding: utf-8
permalink: /:year/:month/:day/:title/

# other links
twitter_username:  
facebook_username: kartik.asooja
github_username:  kasooja
email: asooja@gmail.com
weibo_username: 
zhihu_username: 
linkedIn_username: kartik-asooja-9b554910
dribbble_username: 

description_footer:

# comments
# two ways to comment, only choose one, and use your own short name
duoshuo_shortname: #kablog
disqus_shortname: #gaohaoyang

# statistic analysis
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
baidu_tongji_id: #cf8506e0ef223e57ff6239944e5d46a4
google_analytics_id: UA-91684739-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
